# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length='500', verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Post title'),
        ),
    ]
