# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.TextField(max_length=500, verbose_name='Profile Information'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to='clients.Client', verbose_name='Profile User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(max_length=100, verbose_name='status'),
        ),
    ]
