language: python
addons:
  postgresql: "9.4"
services:
   - postgresql
python:
    - 3.5.0
install: "pip install -r requirements.txt"
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
